**** A Python library and CLI tools for iPod shuffle 4th generation with VoiceOver(TTS) support

project [[https://github.com/nims11/IPod-Shuffle-4g][IPod-Shuffle-4g]] inspire me.

** Dependencies
   Python 3

   [[https://bitbucket.org/lazka/mutagen][mutagen]]>=1.27

   [[https://github.com/saffsd/langid.py][langid]]

   [[http://picospeaker.tk/readme.php][svox(PicoSpeaker)]]

** Installation
*** Gentoo/Linux

    app-accessibility/svox in Overlay "ikelos"

    dev-python/ipodshuffle in Overlay "observer"

    use layman add overlays first, then emerge ipodshuffle

** PyPi
   #+BEGIN_SRC
   pip install ipodshuffle
   #+END_SRC


** Usage as a program
*** sync
    major tool. sync from src_path to your device, it will log file mtime, size and checksum,
    #+BEGIN_SRC
    shuffle.py fun=sync src=src_path base=ipodshuffle_path ttsengine=sovx langs=en-GB
    #+END_SRC

    The folder src_path should have three child folders in it: "music", "podcasts" and "audiobooks".

    In "music": all folders and child folders will be iPod's NORMAL playlists, title is folder name, if VoiceOver is enabled.

    In "podcasts": only child folder will be PODCAST playlists.

    In "audiobooks": child files and folders will be AUDIOBOOK playlists, but child folder of child folder wouldn't.

   Directory structure
*** show
    show information
    #+BEGIN_SRC
    shuffle.py fun=show base=ipodshuffle_path
    #+END_SRC
    
*** set
    #+BEGIN_SRC
    shuffle.py fun=set base=ipodshuffle_path enable_voiceover=true max_volume=12
    #+END_SRC

** TTS things
    Program use Python library langid to figure out track and playlist title text langguage,

    but not work perfect,use "langs=lang1,lang2..." will limitt langguages range.

    For now, have two TTS engine wrapper:
*** Sovx:
    sovx pico2wave. Make sure you already installed it.
    example:
    #+BEGIN_SRC
    shuffle.py fun=sync src=src_path base=ipodshuffle_path ttsengine=sovx langs=en-US
    #+END_SRC

*** Voicerss
    a http tts engine. support lot of languages(include CJK).
    For now, dayily request is free for 350 times, but use this need to regitstration to get an API key,
    the website: http://www.voicerss.org
    
    example:
    #+BEGIN_SRC
    shuffle.py fun=sync src=src_path base=ipod_path ttsengine=voicerss langs=zh-cn,en-gb,ja-jp key=sa9ofsa09f8s09sa8f0sa98sa0f9s8
    #+END_SRC
    

*** Usage as a Python library
    Only tested in Python 3

    example see ipodshuffle/tools/sync.py

** License
   MIT
