#!/usr/bin/env python3

# -*- coding: utf-8 -*-
import re
import sys
import os

try:
    from ipodshuffle.tools.teresa import main

except ImportError:
    dir_ = os.path.dirname(os.path.realpath(__file__))
    sys.path.insert(0, dir_)
    sys.path.insert(0, os.path.abspath(os.path.join(dir_, "../..")))

    from ipodshuffle.tools.teresa import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
